import "./globals.css"
import { Poppins} from '@next/font/google'
export const font = Poppins({
  subsets: ['latin'],
  weight: ['400',  '700'],
});



import ResultProvider from "./context/resultContext";

export const metadata = {
  title: "Hasib",
  description: "Generated by Ferdjani Ziad",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      
      <body  className={font.className}>
        <ResultProvider>{children}</ResultProvider>
      </body>
    </html>
  );
}
