import "./globals.css";
import { Poppins } from "@next/font/google";
export const font = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
});

import ResultProvider from "./context/resultContext";

export const metadata = {
  title: "Alhaseb",
  description: "Generated by Ferdjani Ziad",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* add meta tag */}
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/public/favicon.ico" />
      </head>
      <body className={font.className}>
        <>
          <ResultProvider>{children}</ResultProvider>
        </>
      </body>
    </html>
  );
}
